name: release

on:
  push:
    branches:
      - "v*"
    tags:
      - "*"

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    strategy:
      matrix:
        slim: [ true, false ]
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space on Ubuntu runner
        uses: kfir4444/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Prepare Docker
        run: |
          sudo mkdir -p /mnt/docker
          echo '{ "data-root": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
          sudo systemctl daemon-reload
          sudo systemctl restart docker
          docker info

      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare workspace
        run: |
          sudo mkdir -p /mnt/ragflow
          sudo chmod 777 /mnt/ragflow
          sudo mv * .* /mnt/ragflow

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: /mnt/ragflow
          push: true
          tags: ${{ matrix.slim == true && format('oceanbase/ragflow:{0}-slim', github.ref_name) || format('oceanbase/ragflow:{0}', github.ref_name) }}
          file: /mnt/ragflow/Dockerfile
          build-args: ${{ matrix.slim == true && 'LIGHTEN=1' || '' }}
          platforms: linux/amd64
